(delete 'font initial-frame-alist)
(delete 'width initial-frame-alist)
(delete 'height initial-frame-alist)
(delete 'top initial-frame-alist)
(delete 'left initial-frame-alist)
(setq initial-frame-alist (append (list
'(font . "MS Gothic 16")
'(width . 80)
'(height . 40)
'(top . 108)
'(left . 319))
initial-frame-alist))
(delete 'font default-frame-alist)
(delete 'width default-frame-alist)
(delete 'height default-frame-alist)
(delete 'top default-frame-alist)
(delete 'left default-frame-alist)
(defun mmemo-set-default-frame ()
(setq default-frame-alist (append (list
'(font . "MS Gothic 16")
'(width . 80)
'(height . 40)
'(top . 108)
'(left . 319))
default-frame-alist))
)
(add-hook 'after-init-hook 'mmemo-set-default-frame)
